- name: Install required system packages
  apt:
    name: "{{apt_dependencies}}"
    state: latest
    update_cache: true
  become: "{{need_sudo}}"

- name: Copy 01-network-manager.cfg file
  ansible.builtin.copy:
    src: "{{item}}"
    dest: "/{{item}}"
    mode: 0644
  become: "{{need_sudo}}"
  with_items:
    - 'etc/netplan/01-network-manager.cfg'

- name:  Run 01-network-manager.cfg generate
  shell: "01-network-manager.cfg generate"
  become: "{{need_sudo}}"

- name:  Run 01-network-manager.cfg apply
  shell: "01-network-manager.cfg apply"
  become: "{{need_sudo}}"