#!/usr/bin/env python3

import pathlib
import json

motd_message = """

  _    _           _       _                                       _                   _              _____                                    _ _
 | |  | |         | |     | |                                     | |                 | |            |  __ \                                  | | |
 | |  | |_ __   __| | __ _| |_ ___   _   _  ___  _   _ _ __       | |_   _ _ __  _   _| |_ ___ _ __  | |__) |_ _ ___ _____      _____  _ __ __| | |
 | |  | | '_ \ / _` |/ _` | __/ _ \ | | | |/ _ \| | | | '__|  _   | | | | | '_ \| | | | __/ _ \ '__| |  ___/ _` / __/ __\ \ /\ / / _ \| '__/ _` | |
 | |__| | |_) | (_| | (_| | ||  __/ | |_| | (_) | |_| | |    | |__| | |_| | |_) | |_| | ||  __/ |    | |  | (_| \__ \__ \\ V  V / (_) | | | (_| |_|
  \____/| .__/ \__,_|\__,_|\__\___|  \__, |\___/ \__,_|_|     \____/ \__,_| .__/ \__, |\__\___|_|    |_|   \__,_|___/___/ \_/\_/ \___/|_|  \__,_(_)
        | |                           __/ |                               | |     __/ |
        |_|                          |___/                                |_|    |___/

Run as user {{user_name}}:
"{{jupyterlab.virtualenv}}/bin/jupyter server password"
to update the password. (The default password is "{{jupyterlab.password}}")
"""

server_config_file = pathlib.Path("{{jupyter_server_config_file}}")

if server_config_file.exists():
    with open(server_config_file) as f:
        hashed_server_password = json.load(f)["ServerApp"]["password"]
    # server_hashed_password was set by ansible (see motd.yml)
    if hashed_server_password == "{{server_hashed_password}}":
        print(motd_message)
