- name: Setup EC2 instance
  hosts: ec2
  vars:
      ansible_python_interpreter: /usr/bin/python3
  remote_user: ubuntu

  tasks:
  - import_tasks: slc_setup_tasks.yml
    become: yes
  - import_tasks: install_docker.yml
    become: yes
