Resources:
  VMBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
    DeletionPolicy: Retain
  BucketPolicy:
    Type: 'AWS::S3::BucketPolicy'
    Properties:
      PolicyDocument:
        Id: VMBucket_Policy
        Version: 2012-10-17
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref VMBucket
                - /*
      Bucket: !Ref VMBucket
Outputs:
  S3BucketSecureURL:
    Value: !Join
      - ''
      - - 'https://'
        - !GetAtt
          - VMBucket
          - DomainName
    Description: Name of S3 bucket
